repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        verbose: true
        additional_dependencies: ['types-PyYAML']
  - repo: https://github.com/pycqa/pydocstyle.git
    rev: 6.3.0
    hooks:
      - id: pydocstyle
