name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: pymol-movie:latest
        outputs: type=docker,dest=/tmp/pymol-movie.tar
    -
      name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pymol-movie
        path: /tmp/pymol-movie.tar
        
  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pymol-movie
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/pymol-movie.tar
          docker image ls -a
          
